project_id = "fqeruutxahrrxjusxndl"

[functions.generate-meal-plan]
verify_jwt = false

[functions.generate-grocery-list]
verify_jwt = false

[functions.send-patient-magic-link]
verify_jwt = true

[functions.generate-recipe]
verify_jwt = false
